<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <RootNamespace>MesRelayGateway.Gui</RootNamespace>
    <AssemblyName>MesRelayGatewayGui</AssemblyName>
    <UseWPF>true</UseWPF>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <InvariantGlobalization>true</InvariantGlobalization>

    <RuntimeIdentifiers>win-x64;win-x86</RuntimeIdentifiers>
    <SelfContained>false</SelfContained>
    <PublishSingleFile>true</PublishSingleFile>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\MesRelayGateway.Core\MesRelayGateway.Core.csproj" />
  </ItemGroup>

</Project>
